openapi: 3.0.0
info:
  title: Documentation for GoTo api
  version: 0.0.1
servers:
- url: http://localhost:8080
  description: Dev server
paths:
  /api/v1/login:
    post:
      summary: Logs in and returns the authentication  cookie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      security: []    # no authentication
      responses:
        '200':
          description: logged in
          headers:
            Set-Cookie:
              schema:
                type: string
                example: sessionId=abcde12345;
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: access denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /api/v1/signup:
    post:
      summary: Signs up and returns the authentication  cookie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      security: []    # no authentication
      responses:
        '201':
          description: Created a new account
          headers:
            Set-Cookie:
              schema:
                type: string
                example: sessionId=abcde12345;
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '401':
          description: sign up error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
  /api/v1/logout:
    delete:
      summary: Logs out by deleting sessionId cookie
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Ok
          headers:
            Set-Cookie:
              schema:
                type: string
  /api/v1/places:
    get:
      summary: Returns list of places
      security: []    # no authentication
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceList'
    post:
      summary: Create a new place
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Place'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
  /api/v1/auth:
    get:
      summary: Checks if you have valid sessionId
      security:
        - cookieAuth: []
      responses:
        '200':
          description: You have valid sessionId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: You dont have valid sessionId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /api/v1/user:
    get:
      summary: Returns json with user data
      security:
        - cookieAuth: []
      responses:
        '200':
          description: User is authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserInfoResponse'
        '401':
          description: User is unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserInfoResponse'


components:
  schemas:
    LoginRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        error:
          type: string
    GetUserInfoResponse:
      type: object
      properties:
        error:
          type: string
        user:
            $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        login:
          type: string
    SignupRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
    SignupResponse:
      type: object
      properties:
        error:
          type: string
    Place:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        rating:
          type: number
        cost:
          type: string
        imageUrl:
          type: string
    PlaceList:
      type: object
      properties:
        body:
          type: array
          items:
            $ref: '#/components/schemas/Place'

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId


security:
  - cookieAuth: []
